import { clipboard, contextBridge, ipcRenderer, shell, type IpcRendererEvent } from 'electron';
import {
  AJUSTES_CHANNELS,
  ANEXOS_CHANNELS,
  APP_CHANNELS,
  ATUALIZACAO_CHANNELS,
  COPY_CHANNELS,
  EXPLORADOR_CHANNELS,
  CONTATOS_CHANNELS,
  DOCUMENTOS_CHANNELS,
  EXPORT_CHANNELS,
  GITHUB_CHANNELS,
  IMAGENS_CHANNELS,
  KANBAN_CHANNELS,
  LINKS_CHANNELS,
  N8N_CHANNELS,
  PENSAMENTOS_CHANNELS,
  TODO_CHANNELS,
  IA_CHANNELS,
  PUSH_CHANNEL,
  QUADRO_CHANNELS,
  RELATORIOS_CHANNELS,
  ROTEIROS_CHANNELS,
  TRAFEGO_CHANNELS,
  SERVIDORES_CHANNELS,
  SHEETS_CHANNELS,
  VIDEOS_CHANNELS,
  WHATSAPP_CHANNELS,
} from '../shared/ipcChannels';
import type {
  IrisEvent,
  IrisEventPayload,
  IrisEventTopic,
  Unsubscribe,
} from '../shared/types/events.types';
import type { IrisApi } from '../shared/types/preload-api.types';

function openExternalLink(url: string): void {
  if (/^https?:\/\//i.test(url)) {
    void shell.openExternal(url);
  }
}

// Vários assinantes lógicos compartilham um único canal físico; sem isto o
// EventEmitter reclama ao passar de 10 listeners.
ipcRenderer.setMaxListeners(64);

/**
 * O contextBridge não consegue devolver a identidade do listener para um
 * removeListener do lado do renderer, então quem cancela é esta closure.
 */
function subscribe<T extends IrisEventTopic>(
  topic: T,
  callback: (payload: IrisEventPayload<T>) => void,
): Unsubscribe {
  const handler = (_event: IpcRendererEvent, incoming: IrisEvent): void => {
    if (!incoming || incoming.topic !== topic) return;
    try {
      callback(incoming.payload as IrisEventPayload<T>);
    } catch (error) {
      // Um listener que lança não pode derrubar os outros assinantes do canal.
      console.error(`[irisAPI.events] listener falhou em "${topic}"`, error);
    }
  };

  ipcRenderer.on(PUSH_CHANNEL, handler);

  let ativo = true;
  return () => {
    if (!ativo) return; // cancelamento idempotente
    ativo = false;
    ipcRenderer.off(PUSH_CHANNEL, handler);
  };
}

const irisAPI: IrisApi = {
  kanban: {
    getBoard: () => ipcRenderer.invoke(KANBAN_CHANNELS.getBoard),
    createColumn: (input) => ipcRenderer.invoke(KANBAN_CHANNELS.createColumn, input),
    renameColumn: (input) => ipcRenderer.invoke(KANBAN_CHANNELS.renameColumn, input),
    reorderColumns: (input) => ipcRenderer.invoke(KANBAN_CHANNELS.reorderColumns, input),
    deleteColumn: (columnId) => ipcRenderer.invoke(KANBAN_CHANNELS.deleteColumn, columnId),
    createCard: (input) => ipcRenderer.invoke(KANBAN_CHANNELS.createCard, input),
    updateCard: (input) => ipcRenderer.invoke(KANBAN_CHANNELS.updateCard, input),
    deleteCard: (cardId) => ipcRenderer.invoke(KANBAN_CHANNELS.deleteCard, cardId),
    moveCard: (input) => ipcRenderer.invoke(KANBAN_CHANNELS.moveCard, input),
  },
  quadro: {
    getState: () => ipcRenderer.invoke(QUADRO_CHANNELS.getState),
    createBlock: (input) => ipcRenderer.invoke(QUADRO_CHANNELS.createBlock, input),
    updateBlock: (input) => ipcRenderer.invoke(QUADRO_CHANNELS.updateBlock, input),
    moveBlock: (input) => ipcRenderer.invoke(QUADRO_CHANNELS.moveBlock, input),
    deleteBlock: (blockId) => ipcRenderer.invoke(QUADRO_CHANNELS.deleteBlock, blockId),
    createConnection: (input) => ipcRenderer.invoke(QUADRO_CHANNELS.createConnection, input),
    deleteConnection: (connectionId) => ipcRenderer.invoke(QUADRO_CHANNELS.deleteConnection, connectionId),
    updateViewport: (viewport) => ipcRenderer.invoke(QUADRO_CHANNELS.updateViewport, viewport),
    updateBoardName: (boardName) => ipcRenderer.invoke(QUADRO_CHANNELS.updateBoardName, boardName),
  },
  sheets: {
    getFile: () => ipcRenderer.invoke(SHEETS_CHANNELS.getFile),
    detectImport: () => ipcRenderer.invoke(SHEETS_CHANNELS.detectImport),
    commitImport: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.commitImport, input),
    createTable: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.createTable, input),
    renameTable: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.renameTable, input),
    setTableVisibility: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.setTableVisibility, input),
    addColumn: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.addColumn, input),
    updateColumn: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.updateColumn, input),
    deleteColumn: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.deleteColumn, input),
    createRow: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.createRow, input),
    updateRow: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.updateRow, input),
    deleteRow: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.deleteRow, input),
    deleteRows: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.deleteRows, input),
    deleteTable: (input) => ipcRenderer.invoke(SHEETS_CHANNELS.deleteTable, input),
  },
  system: {
    copyToClipboard: (text) => clipboard.writeText(text),
    openExternalLink,
    plataforma: process.platform === 'linux' || process.platform === 'darwin' ? process.platform : 'win32',
    primeiraTela: (ms) => ipcRenderer.send(APP_CHANNELS.primeiraTela, ms),
  },
  contatos: {
    getFile: () => ipcRenderer.invoke(CONTATOS_CHANNELS.getFile),
    salvarPessoa: (pessoa) => ipcRenderer.invoke(CONTATOS_CHANNELS.salvarPessoa, pessoa),
    salvarEmpresa: (empresa) => ipcRenderer.invoke(CONTATOS_CHANNELS.salvarEmpresa, empresa),
    excluirContato: (ref) => ipcRenderer.invoke(CONTATOS_CHANNELS.excluirContato, ref),
    arquivarContato: (ref, arquivado) => ipcRenderer.invoke(CONTATOS_CHANNELS.arquivarContato, ref, arquivado),
    moverNoFunil: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.moverNoFunil, input),
    salvarEtapas: (etapas) => ipcRenderer.invoke(CONTATOS_CHANNELS.salvarEtapas, etapas),
    registrarInteracao: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.registrarInteracao, input),
    editarInteracao: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.editarInteracao, input),
    excluirInteracao: (id) => ipcRenderer.invoke(CONTATOS_CHANNELS.excluirInteracao, id),
    salvarModelo: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.salvarModelo, input),
    duplicarModelo: (id) => ipcRenderer.invoke(CONTATOS_CHANNELS.duplicarModelo, id),
    excluirModelo: (id) => ipcRenderer.invoke(CONTATOS_CHANNELS.excluirModelo, id),
    criarContrato: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.criarContrato, input),
    atualizarContrato: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.atualizarContrato, input),
    duplicarContrato: (id) => ipcRenderer.invoke(CONTATOS_CHANNELS.duplicarContrato, id),
    excluirContrato: (id) => ipcRenderer.invoke(CONTATOS_CHANNELS.excluirContrato, id),
    exportarPdf: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.exportarPdf, input),
    leadsStatus: () => ipcRenderer.invoke(CONTATOS_CHANNELS.leadsStatus),
    salvarLeadsConfig: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.salvarLeadsConfig, input),
    gerarChaveFormulario: () => ipcRenderer.invoke(CONTATOS_CHANNELS.gerarChaveFormulario),
    gerarChaveIris: () => ipcRenderer.invoke(CONTATOS_CHANNELS.gerarChaveIris),
    definirChaveIris: (valor) => ipcRenderer.invoke(CONTATOS_CHANNELS.definirChaveIris, valor),
    copiarChaveIris: () => ipcRenderer.invoke(CONTATOS_CHANNELS.copiarChaveIris),
    testarNuvem: () => ipcRenderer.invoke(CONTATOS_CHANNELS.testarNuvem),
    buscarAgora: () => ipcRenderer.invoke(CONTATOS_CHANNELS.buscarAgora),
    enviarTeste: () => ipcRenderer.invoke(CONTATOS_CHANNELS.enviarTeste),
    marcarVisto: (ids) => ipcRenderer.invoke(CONTATOS_CHANNELS.marcarVisto, ids),
    descartarLead: (input) => ipcRenderer.invoke(CONTATOS_CHANNELS.descartarLead, input),
    repontuar: () => ipcRenderer.invoke(CONTATOS_CHANNELS.repontuar),
    contarNaoVistos: () => ipcRenderer.invoke(CONTATOS_CHANNELS.contarNaoVistos),
    salvarRelatorioLeads: (relatorio, exportou) => ipcRenderer.invoke(CONTATOS_CHANNELS.salvarRelatorioLeads, relatorio, exportou),
    excluirRelatorioLeads: (id) => ipcRenderer.invoke(CONTATOS_CHANNELS.excluirRelatorioLeads, id),
    criarFluxoN8n: (cenario) => ipcRenderer.invoke(CONTATOS_CHANNELS.criarFluxoN8n, cenario),
    testarFluxoN8n: () => ipcRenderer.invoke(CONTATOS_CHANNELS.testarFluxoN8n),
  },
  whatsapp: {
    getFile: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.getFile),
    status: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.status),
    salvarConfig: (input) => ipcRenderer.invoke(WHATSAPP_CHANNELS.salvarConfig, input),
    definirSegredo: (qual, valor) => ipcRenderer.invoke(WHATSAPP_CHANNELS.definirSegredo, qual, valor),
    removerCredenciais: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.removerCredenciais),
    gerarChaveWebhook: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.gerarChaveWebhook),
    copiarChaveWebhook: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.copiarChaveWebhook),
    enderecos: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.enderecos),
    copiarEndereco: (origem, via) => ipcRenderer.invoke(WHATSAPP_CHANNELS.copiarEndereco, origem, via),
    configurarWebhook: (provedor, via) => ipcRenderer.invoke(WHATSAPP_CHANNELS.configurarWebhook, provedor, via),
    testar: (provedor) => ipcRenderer.invoke(WHATSAPP_CHANNELS.testar, provedor),
    conferirNumero: (provedor, numero) => ipcRenderer.invoke(WHATSAPP_CHANNELS.conferirNumero, provedor, numero),
    listarTemplates: () => ipcRenderer.invoke(WHATSAPP_CHANNELS.listarTemplates),
    enviar: (input) => ipcRenderer.invoke(WHATSAPP_CHANNELS.enviar, input),
    reenviar: (id) => ipcRenderer.invoke(WHATSAPP_CHANNELS.reenviar, id),
    sincronizarConversa: (ref) => ipcRenderer.invoke(WHATSAPP_CHANNELS.sincronizarConversa, ref),
    marcarLidas: (alvo) => ipcRenderer.invoke(WHATSAPP_CHANNELS.marcarLidas, alvo),
    ligarNumero: (numero, ref) => ipcRenderer.invoke(WHATSAPP_CHANNELS.ligarNumero, numero, ref),
    excluirMensagem: (id) => ipcRenderer.invoke(WHATSAPP_CHANNELS.excluirMensagem, id),
    salvarModelo: (input) => ipcRenderer.invoke(WHATSAPP_CHANNELS.salvarModelo, input),
    excluirModelo: (id) => ipcRenderer.invoke(WHATSAPP_CHANNELS.excluirModelo, id),
    criarLote: (input) => ipcRenderer.invoke(WHATSAPP_CHANNELS.criarLote, input),
    mudarLote: (id, acao) => ipcRenderer.invoke(WHATSAPP_CHANNELS.mudarLote, id, acao),
    previaFluxoN8n: (tipo, cenario) => ipcRenderer.invoke(WHATSAPP_CHANNELS.previaFluxoN8n, tipo, cenario),
    copiarFluxoN8n: (tipo, cenario) => ipcRenderer.invoke(WHATSAPP_CHANNELS.copiarFluxoN8n, tipo, cenario),
    criarFluxoN8n: (tipo, cenario) => ipcRenderer.invoke(WHATSAPP_CHANNELS.criarFluxoN8n, tipo, cenario),
  },
  documentos: {
    abrirPdf: (filePath) => ipcRenderer.invoke(DOCUMENTOS_CHANNELS.abrirPdf, filePath),
  },
  export: {
    resumo: () => ipcRenderer.invoke(EXPORT_CHANNELS.resumo),
    exportar: (escopo, formato) => ipcRenderer.invoke(EXPORT_CHANNELS.exportar, escopo, formato),
    escolherImportacao: () => ipcRenderer.invoke(EXPORT_CHANNELS.escolherImportacao),
    aplicarImportacao: (modulos) => ipcRenderer.invoke(EXPORT_CHANNELS.aplicarImportacao, modulos),
    cancelarImportacao: () => ipcRenderer.invoke(EXPORT_CHANNELS.cancelarImportacao),
    ultimaCopia: () => ipcRenderer.invoke(EXPORT_CHANNELS.ultimaCopia),
    desfazerImportacao: () => ipcRenderer.invoke(EXPORT_CHANNELS.desfazerImportacao),
    abrirPastaDeCopias: () => ipcRenderer.invoke(EXPORT_CHANNELS.abrirPastaDeCopias),
  },
  links: {
    getLinks: () => ipcRenderer.invoke(LINKS_CHANNELS.getLinks),
    createLink: (input) => ipcRenderer.invoke(LINKS_CHANNELS.createLink, input),
    updateLink: (input) => ipcRenderer.invoke(LINKS_CHANNELS.updateLink, input),
    deleteLink: (linkId) => ipcRenderer.invoke(LINKS_CHANNELS.deleteLink, linkId),
    reorderLinks: (orderedLinkIds) => ipcRenderer.invoke(LINKS_CHANNELS.reorderLinks, orderedLinkIds),
  },
  copy: {
    getSnippets: () => ipcRenderer.invoke(COPY_CHANNELS.getSnippets),
    createSnippet: (input) => ipcRenderer.invoke(COPY_CHANNELS.createSnippet, input),
    updateSnippet: (input) => ipcRenderer.invoke(COPY_CHANNELS.updateSnippet, input),
    deleteSnippet: (snippetId) => ipcRenderer.invoke(COPY_CHANNELS.deleteSnippet, snippetId),
    importTxt: () => ipcRenderer.invoke(COPY_CHANNELS.importTxt),
  },
  roteiros: {
    getFile: () => ipcRenderer.invoke(ROTEIROS_CHANNELS.getFile),
    criarRoteiro: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.criarRoteiro, input),
    atualizarRoteiro: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.atualizarRoteiro, input),
    mudarStatus: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.mudarStatus, input),
    aprovarRoteiro: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.aprovarRoteiro, input),
    excluirRoteiro: (roteiroId) => ipcRenderer.invoke(ROTEIROS_CHANNELS.excluirRoteiro, roteiroId),
    duplicarRoteiro: (roteiroId) => ipcRenderer.invoke(ROTEIROS_CHANNELS.duplicarRoteiro, roteiroId),
    salvarChecklistPadrao: (itens) => ipcRenderer.invoke(ROTEIROS_CHANNELS.salvarChecklistPadrao, itens),
    salvarVersao: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.salvarVersao, input),
    restaurarVersao: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.restaurarVersao, input),
    criarAdaptacao: (input) => ipcRenderer.invoke(ROTEIROS_CHANNELS.criarAdaptacao, input),
  },
  trafego: {
    getFile: () => ipcRenderer.invoke(TRAFEGO_CHANNELS.getFile),
    salvarConta: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.salvarConta, input),
    excluirConta: (contaId) => ipcRenderer.invoke(TRAFEGO_CHANNELS.excluirConta, contaId),
    salvarSite: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.salvarSite, input),
    excluirSite: (siteId) => ipcRenderer.invoke(TRAFEGO_CHANNELS.excluirSite, siteId),
    criarCampanha: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.criarCampanha, input),
    atualizarCampanha: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.atualizarCampanha, input),
    moverCampanha: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.moverCampanha, input),
    excluirCampanha: (campanhaId) => ipcRenderer.invoke(TRAFEGO_CHANNELS.excluirCampanha, campanhaId),
    duplicarCampanha: (campanhaId) => ipcRenderer.invoke(TRAFEGO_CHANNELS.duplicarCampanha, campanhaId),
    salvarRegistro: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.salvarRegistro, input),
    removerRegistro: (input) => ipcRenderer.invoke(TRAFEGO_CHANNELS.removerRegistro, input),
    importarRegistros: (campanhaId) => ipcRenderer.invoke(TRAFEGO_CHANNELS.importarRegistros, campanhaId),
  },
  ia: {
    getConfig: () => ipcRenderer.invoke(IA_CHANNELS.getConfig),
    salvarProvedor: (input) => ipcRenderer.invoke(IA_CHANNELS.salvarProvedor, input),
    salvarPadroes: (input) => ipcRenderer.invoke(IA_CHANNELS.salvarPadroes, input),
    testarProvedor: (id) => ipcRenderer.invoke(IA_CHANNELS.testarProvedor, id),
    listarModelos: (id, forcar) => ipcRenderer.invoke(IA_CHANNELS.listarModelos, id, forcar),
    gerarTexto: (pedido) => ipcRenderer.invoke(IA_CHANNELS.gerarTexto, pedido),
    referenciasDoComputador: () => ipcRenderer.invoke(IA_CHANNELS.referenciasDoComputador),
    descreverReferencia: (ref) => ipcRenderer.invoke(IA_CHANNELS.descreverReferencia, ref),
    gerarImagem: (input) => ipcRenderer.invoke(IA_CHANNELS.gerarImagem, input),
    cancelarTarefa: (tarefaId) => ipcRenderer.invoke(IA_CHANNELS.cancelarTarefa, tarefaId),
    listarTarefas: () => ipcRenderer.invoke(IA_CHANNELS.listarTarefas),
    dispensarTarefa: (tarefaId) => ipcRenderer.invoke(IA_CHANNELS.dispensarTarefa, tarefaId),
    limparTarefas: () => ipcRenderer.invoke(IA_CHANNELS.limparTarefas),
    listarGaleria: () => ipcRenderer.invoke(IA_CHANNELS.listarGaleria),
    abrirImagem: (id) => ipcRenderer.invoke(IA_CHANNELS.abrirImagem, id),
    excluirImagem: (id) => ipcRenderer.invoke(IA_CHANNELS.excluirImagem, id),
    exportarImagem: (id) => ipcRenderer.invoke(IA_CHANNELS.exportarImagem, id),
    salvarNaBiblioteca: (id, destino) => ipcRenderer.invoke(IA_CHANNELS.salvarNaBiblioteca, id, destino),
    vincularPostagem: (id, postagem) => ipcRenderer.invoke(IA_CHANNELS.vincularPostagem, id, postagem),
  },
  todo: {
    getFile: () => ipcRenderer.invoke(TODO_CHANNELS.getFile),
    criarChecklist: (input) => ipcRenderer.invoke(TODO_CHANNELS.criarChecklist, input),
    atualizarChecklist: (input) => ipcRenderer.invoke(TODO_CHANNELS.atualizarChecklist, input),
    excluirChecklist: (checklistId) => ipcRenderer.invoke(TODO_CHANNELS.excluirChecklist, checklistId),
    duplicarChecklist: (checklistId) => ipcRenderer.invoke(TODO_CHANNELS.duplicarChecklist, checklistId),
    arquivarChecklist: (input) => ipcRenderer.invoke(TODO_CHANNELS.arquivarChecklist, input),
    reordenarChecklists: (checklistIds) => ipcRenderer.invoke(TODO_CHANNELS.reordenarChecklists, checklistIds),
    adicionarItens: (input) => ipcRenderer.invoke(TODO_CHANNELS.adicionarItens, input),
    atualizarItem: (input) => ipcRenderer.invoke(TODO_CHANNELS.atualizarItem, input),
    removerItem: (input) => ipcRenderer.invoke(TODO_CHANNELS.removerItem, input),
    reordenarItens: (input) => ipcRenderer.invoke(TODO_CHANNELS.reordenarItens, input),
    marcarTodos: (input) => ipcRenderer.invoke(TODO_CHANNELS.marcarTodos, input),
    limparConcluidos: (checklistId) => ipcRenderer.invoke(TODO_CHANNELS.limparConcluidos, checklistId),
    enviarAoKanban: (input) => ipcRenderer.invoke(TODO_CHANNELS.enviarAoKanban, input),
  },
  pensamentos: {
    getPensamentos: () => ipcRenderer.invoke(PENSAMENTOS_CHANNELS.getPensamentos),
    createPensamento: (input) => ipcRenderer.invoke(PENSAMENTOS_CHANNELS.createPensamento, input),
    updatePensamento: (input) => ipcRenderer.invoke(PENSAMENTOS_CHANNELS.updatePensamento, input),
    deletePensamento: (pensamentoId) =>
      ipcRenderer.invoke(PENSAMENTOS_CHANNELS.deletePensamento, pensamentoId),
    togglePin: (pensamentoId) => ipcRenderer.invoke(PENSAMENTOS_CHANNELS.togglePin, pensamentoId),
    moverPensamento: (input) => ipcRenderer.invoke(PENSAMENTOS_CHANNELS.moverPensamento, input),
    setViewport: (viewport) => ipcRenderer.invoke(PENSAMENTOS_CHANNELS.setViewport, viewport),
  },
  explorador: {
    getRaizes: () => ipcRenderer.invoke(EXPLORADOR_CHANNELS.getRaizes),
    adicionarRaiz: () => ipcRenderer.invoke(EXPLORADOR_CHANNELS.adicionarRaiz),
    removerRaiz: (raizId) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.removerRaiz, raizId),
    listarDiretorio: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.listarDiretorio, input),
    criar: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.criar, input),
    renomear: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.renomear, input),
    mover: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.mover, input),
    excluir: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.excluir, input),
    revelarNoSistema: (caminho) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.revelarNoSistema, caminho),
    abrirNoSistema: (caminho) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.abrirNoSistema, caminho),
    getBiblioteca: () => ipcRenderer.invoke(EXPLORADOR_CHANNELS.getBiblioteca),
    adicionarRecurso: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.adicionarRecurso, input),
    adicionarRecursosPorDialogo: (colecaoId) =>
      ipcRenderer.invoke(EXPLORADOR_CHANNELS.adicionarRecursosPorDialogo, colecaoId),
    atualizarRecurso: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.atualizarRecurso, input),
    removerRecurso: (recursoId) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.removerRecurso, recursoId),
    salvarColecao: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.salvarColecao, input),
    excluirColecao: (colecaoId) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.excluirColecao, colecaoId),
    limparRecentes: () => ipcRenderer.invoke(EXPLORADOR_CHANNELS.limparRecentes),
    buscar: (input) => ipcRenderer.invoke(EXPLORADOR_CHANNELS.buscar, input),
  },
  servidores: {
    getState: () => ipcRenderer.invoke(SERVIDORES_CHANNELS.getState),
    criarHttp: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.criarHttp, input),
    criarSsh: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.criarSsh, input),
    atualizar: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.atualizar, input),
    remover: (servidorId) => ipcRenderer.invoke(SERVIDORES_CHANNELS.remover, servidorId),
    checarAgora: (servidorId) => ipcRenderer.invoke(SERVIDORES_CHANNELS.checarAgora, servidorId),
    checarTodos: () => ipcRenderer.invoke(SERVIDORES_CHANNELS.checarTodos),
    salvarComando: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.salvarComando, input),
    removerComando: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.removerComando, input),
    rodarComando: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.rodarComando, input),
    configHealth: (input) => ipcRenderer.invoke(SERVIDORES_CHANNELS.configHealth, input),
    escolherChave: () => ipcRenderer.invoke(SERVIDORES_CHANNELS.escolherChave),
  },
  n8n: {
    getConfig: () => ipcRenderer.invoke(N8N_CHANNELS.getConfig),
    salvarConfig: (input) => ipcRenderer.invoke(N8N_CHANNELS.salvarConfig, input),
    getSnapshot: () => ipcRenderer.invoke(N8N_CHANNELS.getSnapshot),
    atualizarAgora: () => ipcRenderer.invoke(N8N_CHANNELS.atualizarAgora),
    testarConexao: () => ipcRenderer.invoke(N8N_CHANNELS.testarConexao),
    dispararWorkflow: (input) => ipcRenderer.invoke(N8N_CHANNELS.dispararWorkflow, input),
    alternarAtivo: (input) => ipcRenderer.invoke(N8N_CHANNELS.alternarAtivo, input),
    definirVinculo: (input) => ipcRenderer.invoke(N8N_CHANNELS.definirVinculo, input),
    abrirExecucao: (execucaoId) => ipcRenderer.invoke(N8N_CHANNELS.abrirExecucao, execucaoId),
  },
  github: {
    getConfig: () => ipcRenderer.invoke(GITHUB_CHANNELS.getConfig),
    salvarConfig: (input) => ipcRenderer.invoke(GITHUB_CHANNELS.salvarConfig, input),
    getSnapshot: () => ipcRenderer.invoke(GITHUB_CHANNELS.getSnapshot),
    atualizarAgora: () => ipcRenderer.invoke(GITHUB_CHANNELS.atualizarAgora),
    testarConexao: () => ipcRenderer.invoke(GITHUB_CHANNELS.testarConexao),
    adicionarPasta: () => ipcRenderer.invoke(GITHUB_CHANNELS.adicionarPasta),
    removerPasta: (pastaId) => ipcRenderer.invoke(GITHUB_CHANNELS.removerPasta, pastaId),
    abrirRepo: (url) => ipcRenderer.invoke(GITHUB_CHANNELS.abrirRepo, url),
  },
  ajustes: {
    getAjustes: () => ipcRenderer.invoke(AJUSTES_CHANNELS.getAjustes),
    setModuloInicial: (modulo) => ipcRenderer.invoke(AJUSTES_CHANNELS.setModuloInicial, modulo),
    setAssinatura: (assinatura) => ipcRenderer.invoke(AJUSTES_CHANNELS.setAssinatura, assinatura),
    setPerfil: (perfil) => ipcRenderer.invoke(AJUSTES_CHANNELS.setPerfil, perfil),
    setAtalhos: (atalhos) => ipcRenderer.invoke(AJUSTES_CHANNELS.setAtalhos, atalhos),
    setTema: (tema) => ipcRenderer.invoke(AJUSTES_CHANNELS.setTema, tema),
  },
  videos: {
    getFile: () => ipcRenderer.invoke(VIDEOS_CHANNELS.getFile),
    criarVideo: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.criarVideo, input),
    atualizarVideo: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.atualizarVideo, input),
    moverVideo: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.moverVideo, input),
    arquivarVideo: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.arquivarVideo, input),
    restaurarVideo: (videoId) => ipcRenderer.invoke(VIDEOS_CHANNELS.restaurarVideo, videoId),
    excluirVideo: (videoId) => ipcRenderer.invoke(VIDEOS_CHANNELS.excluirVideo, videoId),
    salvarTag: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.salvarTag, input),
    excluirTag: (tagId) => ipcRenderer.invoke(VIDEOS_CHANNELS.excluirTag, tagId),
    salvarEscala: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.salvarEscala, input),
    excluirEscala: (escalaId) => ipcRenderer.invoke(VIDEOS_CHANNELS.excluirEscala, escalaId),
    definirEscalaPadrao: (escalaId) => ipcRenderer.invoke(VIDEOS_CHANNELS.definirEscalaPadrao, escalaId),
    salvarRede: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.salvarRede, input),
    excluirRede: (redeId) => ipcRenderer.invoke(VIDEOS_CHANNELS.excluirRede, redeId),
    importarDeSheets: (input) => ipcRenderer.invoke(VIDEOS_CHANNELS.importarDeSheets, input),
    listarLinhasImportadas: (tabelaId) => ipcRenderer.invoke(VIDEOS_CHANNELS.listarLinhasImportadas, tabelaId),
    salvarPreferencias: (preferencias) => ipcRenderer.invoke(VIDEOS_CHANNELS.salvarPreferencias, preferencias),
  },
  anexos: {
    escolher: () => ipcRenderer.invoke(ANEXOS_CHANNELS.escolher),
    info: (anexos) => ipcRenderer.invoke(ANEXOS_CHANNELS.info, anexos),
    abrir: (anexo) => ipcRenderer.invoke(ANEXOS_CHANNELS.abrir, anexo),
    revelar: (anexo) => ipcRenderer.invoke(ANEXOS_CHANNELS.revelar, anexo),
    exportar: (anexo) => ipcRenderer.invoke(ANEXOS_CHANNELS.exportar, anexo),
  },
  imagens: {
    getFile: () => ipcRenderer.invoke(IMAGENS_CHANNELS.getFile),
    criarImagem: (input) => ipcRenderer.invoke(IMAGENS_CHANNELS.criarImagem, input),
    atualizarImagem: (input) => ipcRenderer.invoke(IMAGENS_CHANNELS.atualizarImagem, input),
    moverImagem: (input) => ipcRenderer.invoke(IMAGENS_CHANNELS.moverImagem, input),
    arquivarImagem: (input) => ipcRenderer.invoke(IMAGENS_CHANNELS.arquivarImagem, input),
    restaurarImagem: (imagemId) => ipcRenderer.invoke(IMAGENS_CHANNELS.restaurarImagem, imagemId),
    excluirImagem: (imagemId) => ipcRenderer.invoke(IMAGENS_CHANNELS.excluirImagem, imagemId),
  },
  relatorios: {
    getFile: () => ipcRenderer.invoke(RELATORIOS_CHANNELS.getFile),
    criarRelatorio: (input) => ipcRenderer.invoke(RELATORIOS_CHANNELS.criarRelatorio, input),
    salvarRelatorio: (relatorio) => ipcRenderer.invoke(RELATORIOS_CHANNELS.salvarRelatorio, relatorio),
    duplicarRelatorio: (relatorioId) => ipcRenderer.invoke(RELATORIOS_CHANNELS.duplicarRelatorio, relatorioId),
    excluirRelatorio: (relatorioId) => ipcRenderer.invoke(RELATORIOS_CHANNELS.excluirRelatorio, relatorioId),
    salvarCategorias: (input) => ipcRenderer.invoke(RELATORIOS_CHANNELS.salvarCategorias, input),
    exportarPdf: (input) => ipcRenderer.invoke(RELATORIOS_CHANNELS.exportarPdf, input),
  },
  atualizacao: {
    getEstado: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.getEstado),
    verificar: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.verificar),
    atualizar: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.atualizar),
    abrirPagina: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.abrirPagina),
    listarVersoes: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.listarVersoes),
    instalarVersao: (versao) => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.instalarVersao, versao),
    escolherInstalador: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.escolherInstalador),
    instalarArquivo: () => ipcRenderer.invoke(ATUALIZACAO_CHANNELS.instalarArquivo),
  },
  events: {
    on: subscribe,
  },
};

contextBridge.exposeInMainWorld('irisAPI', irisAPI);
